# Generated by Django 5.2.3 on 2025-08-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='listed_by',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='title',
        ),
        migrations.AddField(
            model_name='property',
            name='balcony',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='property',
            name='bath',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='property',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='area_sqft',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
